kind: PersistentVolume
apiVersion: v1
metadata:
  name: zkpv 
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zkpv 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

